
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'nonassocLTGTLEGEleftADDSUBleftMULTDIVleftUMINUSrightPOWADD AND AP AT CLN CM COMMENT COS DEFN DF DIV EQ EXP F GE GT LB LC LE LOG LP LT MULT NUM POW RAT RB RC RP SIN SQRT SUB T TAN TO VARexpr : expr ADD expr\n\t| expr SUB expr\n\t| expr MULT expr\n\t| expr DIV expr\n\t| expr POW exprexpr : LP expr RPexpr : SUB expr %prec UMINUSexpr : rangeexpr : trig_func\n\t\t | exp_functrig_func : trig LP expr RPexp_func : EXP LP expr RP \n\t\t\t\t| LOG LP expr RP\n\t\t\t\t| SQRT LP expr RPtrig : SIN\n\t\t\t| COS\n\t\t\t| TANempty :range : NUM\n\t\t\t| RAT\n\t\t\t| VAR'
    
_lr_action_items = {'LP':([0,2,3,10,11,12,13,14,15,16,17,18,19,20,21,24,25,26,27,],[3,3,3,24,25,26,27,-15,-16,-17,3,3,3,3,3,3,3,3,3,]),'SUB':([0,1,2,3,4,5,6,7,8,9,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[2,18,2,2,-8,-9,-10,-19,-20,-21,2,2,2,2,2,-7,18,2,2,2,2,-1,-2,-3,-4,-5,-6,18,18,18,18,-11,-12,-13,-14,]),'NUM':([0,2,3,17,18,19,20,21,24,25,26,27,],[7,7,7,7,7,7,7,7,7,7,7,7,]),'RAT':([0,2,3,17,18,19,20,21,24,25,26,27,],[8,8,8,8,8,8,8,8,8,8,8,8,]),'VAR':([0,2,3,17,18,19,20,21,24,25,26,27,],[9,9,9,9,9,9,9,9,9,9,9,9,]),'EXP':([0,2,3,17,18,19,20,21,24,25,26,27,],[11,11,11,11,11,11,11,11,11,11,11,11,]),'LOG':([0,2,3,17,18,19,20,21,24,25,26,27,],[12,12,12,12,12,12,12,12,12,12,12,12,]),'SQRT':([0,2,3,17,18,19,20,21,24,25,26,27,],[13,13,13,13,13,13,13,13,13,13,13,13,]),'SIN':([0,2,3,17,18,19,20,21,24,25,26,27,],[14,14,14,14,14,14,14,14,14,14,14,14,]),'COS':([0,2,3,17,18,19,20,21,24,25,26,27,],[15,15,15,15,15,15,15,15,15,15,15,15,]),'TAN':([0,2,3,17,18,19,20,21,24,25,26,27,],[16,16,16,16,16,16,16,16,16,16,16,16,]),'$end':([1,4,5,6,7,8,9,22,28,29,30,31,32,33,38,39,40,41,],[0,-8,-9,-10,-19,-20,-21,-7,-1,-2,-3,-4,-5,-6,-11,-12,-13,-14,]),'ADD':([1,4,5,6,7,8,9,22,23,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[17,-8,-9,-10,-19,-20,-21,-7,17,-1,-2,-3,-4,-5,-6,17,17,17,17,-11,-12,-13,-14,]),'MULT':([1,4,5,6,7,8,9,22,23,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[19,-8,-9,-10,-19,-20,-21,-7,19,19,19,-3,-4,-5,-6,19,19,19,19,-11,-12,-13,-14,]),'DIV':([1,4,5,6,7,8,9,22,23,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[20,-8,-9,-10,-19,-20,-21,-7,20,20,20,-3,-4,-5,-6,20,20,20,20,-11,-12,-13,-14,]),'POW':([1,4,5,6,7,8,9,22,23,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[21,-8,-9,-10,-19,-20,-21,21,21,21,21,21,21,21,-6,21,21,21,21,-11,-12,-13,-14,]),'RP':([4,5,6,7,8,9,22,23,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[-8,-9,-10,-19,-20,-21,-7,33,-1,-2,-3,-4,-5,-6,38,39,40,41,-11,-12,-13,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,2,3,17,18,19,20,21,24,25,26,27,],[1,22,23,28,29,30,31,32,34,35,36,37,]),'range':([0,2,3,17,18,19,20,21,24,25,26,27,],[4,4,4,4,4,4,4,4,4,4,4,4,]),'trig_func':([0,2,3,17,18,19,20,21,24,25,26,27,],[5,5,5,5,5,5,5,5,5,5,5,5,]),'exp_func':([0,2,3,17,18,19,20,21,24,25,26,27,],[6,6,6,6,6,6,6,6,6,6,6,6,]),'trig':([0,2,3,17,18,19,20,21,24,25,26,27,],[10,10,10,10,10,10,10,10,10,10,10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr ADD expr','expr',3,'p_exp1','parseExpr.py',112),
  ('expr -> expr SUB expr','expr',3,'p_exp1','parseExpr.py',113),
  ('expr -> expr MULT expr','expr',3,'p_exp1','parseExpr.py',114),
  ('expr -> expr DIV expr','expr',3,'p_exp1','parseExpr.py',115),
  ('expr -> expr POW expr','expr',3,'p_exp1','parseExpr.py',116),
  ('expr -> LP expr RP','expr',3,'p_exp5','parseExpr.py',123),
  ('expr -> SUB expr','expr',2,'p_exp2','parseExpr.py',130),
  ('expr -> range','expr',1,'p_exp3','parseExpr.py',136),
  ('expr -> trig_func','expr',1,'p_exp4','parseExpr.py',140),
  ('expr -> exp_func','expr',1,'p_exp4','parseExpr.py',141),
  ('trig_func -> trig LP expr RP','trig_func',4,'p_trig_func','parseExpr.py',145),
  ('exp_func -> EXP LP expr RP','exp_func',4,'p_exp_func','parseExpr.py',151),
  ('exp_func -> LOG LP expr RP','exp_func',4,'p_exp_func','parseExpr.py',152),
  ('exp_func -> SQRT LP expr RP','exp_func',4,'p_exp_func','parseExpr.py',153),
  ('trig -> SIN','trig',1,'p_trig','parseExpr.py',159),
  ('trig -> COS','trig',1,'p_trig','parseExpr.py',160),
  ('trig -> TAN','trig',1,'p_trig','parseExpr.py',161),
  ('empty -> <empty>','empty',0,'p_empty','parseExpr.py',165),
  ('range -> NUM','range',1,'p_range','parseExpr.py',169),
  ('range -> RAT','range',1,'p_range','parseExpr.py',170),
  ('range -> VAR','range',1,'p_range','parseExpr.py',171),
]
